# Generated by Django 5.1 on 2024-08-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0002_rename_is_student_customuser_isstudent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('startDateTime', models.DateTimeField(default='1950-03-12 14:00:00')),
            ],
        ),
    ]
