# Generated by Django 5.1 on 2024-08-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0003_skillclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillClass',
        ),
    ]
