# Generated by Django 5.1 on 2024-08-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0005_skillclass_review_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='skillclass',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
